name: pbl_peminjaman_lab
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  image_picker: ^1.0.7
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  firebase_core: ^4.2.1
  flutter_lints: ^5.0.0
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  flutter_launcher_icons: ^0.14.4
  intl_generator: ^0.3.0

  integration_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/avatar/Avatar_Woman.jpg
    - assets/avatar/Avatar_Man.jpg
    - assets/images/logosimple.png
    - assets/images/karakter.png
    - assets/images/Simple.png
    - assets/icons/bot.png
    - assets/icons/lab_icon.png